=== bjovke/freeDiameter/contrib/dict_legacy/dictionary.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dictionary (vendor*, base, application*)>

<!ELEMENT vendor EMPTY>
<!ATTLIST vendor
        id CDATA #REQUIRED
        name CDATA #REQUIRED
>

<!ELEMENT base (command*, typedefn+, avp+)>
<!ATTLIST base
        uri CDATA #IMPLIED
>

<!ELEMENT application (command*, typedefn*, avp*)>
<!ATTLIST application
        id CDATA #REQUIRED
        name CDATA #IMPLIED
        uri CDATA #IMPLIED
>
<!ELEMENT command (requestrules*, answerrules*)>
<!ATTLIST command
        name CDATA #REQUIRED
        code CDATA #REQUIRED
        vendor-id CDATA #IMPLIED
        pbit (0 | 1) "1"
>

<!ELEMENT typedefn EMPTY>
<!ATTLIST typedefn
        type-name ID #REQUIRED
        type-parent IDREF #IMPLIED
        description CDATA #IMPLIED
>
<!ELEMENT avp ((type | grouped), (enum*))>
<!ATTLIST avp
        name ID #REQUIRED
        description CDATA #IMPLIED
        code CDATA #REQUIRED
        may-encrypt (yes | no) "yes"
        mandatory (must | may | mustnot | shouldnot) "may"
        protected (must | may | mustnot | shouldnot) "may"
        vendor-id CDATA #IMPLIED
>
<!ELEMENT type EMPTY>
<!ATTLIST type
        type-name IDREF #REQUIRED
>
<!ELEMENT grouped (gavp+)>
<!ELEMENT gavp EMPTY>
<!ATTLIST gavp
        name IDREF #REQUIRED
        vendor-id CDATA #IMPLIED
>
<!ELEMENT enum EMPTY>
<!ATTLIST enum
        name CDATA #REQUIRED
        code CDATA #REQUIRED
>

<!ELEMENT requestrules (avprule+)>
<!ELEMENT answerrules (avprule+)>

<!ELEMENT avprule EMPTY>
<!ATTLIST avprule
        name IDREF #REQUIRED
        position (first | last | unspecified)  "unspecified"
        maximum CDATA "none"
        minimum CDATA "0"
>

=== bjovke/freeDiameter/contrib/dict_legacy/mobile-ipv4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "dictionary.dtd">
<dictionary>
	<application id="2" name="Mobile IPv4" uri="ftp://ftp.ietf.org/internet-drafts/draft-ietf-aaa-diameter-mobileip-14.txt">
		<command name="AA-Mobile-Node" code="260">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1" />
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1" />
					<avprule name="User-Name" maximum="1" minimum="1" />
					<avprule name="Destination-Realm" maximum="1" minimum="1" />
					<avprule name="Origin-Host" maximum="1" minimum="1" />
					<avprule name="Origin-Realm" maximum="1" minimum="1" />
					<avprule name="MIP-Reg-Request" maximum="1" minimum="1" />
					<avprule name="MIP-MN-AAA-Auth" maximum="1" minimum="1" />
				</required>
				<optional>
					<avprule name="Acct-Multi-Session-Id" maximum="1" />
					<avprule name="Destination-Host" maximum="1" />
					<avprule name="Origin-State-Id" maximum="1" />
					<avprule name="MIP-Mobile-Node-Address" maximum="1" />
					<avprule name="MIP-Home-Agent-Address" maximum="1" />
					<avprule name="MIP-Feature-Vector" maximum="1" />
					<avprule name="MIP-Originating-Foreign-AAA" maximum="1" />
					<avprule name="Authorization-Lifetime" maximum="1" />
					<avprule name="Auth-Session-State" maximum="1" />
					<avprule name="MIP-FA-Challenge" maximum="1" />
					<avprule name="MIP-Candidate-Home-Agent-Host" maximum="1" />
					<avprule name="MIP-Home-Agent-Host" maximum="1" />
					<avprule name="Proxy-Info" />
					<avprule name="Route-Record" />
					<avprule name="AVP" />
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1" />
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1" />
					<avprule name="Result-Code" maximum="1" minimum="1" />
					<avprule name="Origin-Host" maximum="1" minimum="1" />
					<avprule name="Origin-Realm" maximum="1" minimum="1" />
				</required>
				<optional>
					<avprule name="Acct-Multi-Session-Id" maximum="1" />
					<avprule name="User-Name" maximum="1" />
					<avprule name="Authorization-Lifetime" maximum="1" />
					<avprule name="Auth-Session-State" maximum="1" />
					<avprule name="Error-Message" maximum="1" />
					<avprule name="Error-Reporting-Host" maximum="1" />
					<avprule name="Re-Auth-Request-Type" maximum="1" />
					<avprule name="MIP-Feature-Vector" maximum="1" />
					<avprule name="MIP-Reg-Reply" maximum="1" />
					<avprule name="MIP-MN-to-FA-Key" maximum="1" />
					<avprule name="MIP-MN-to-HA-Key" maximum="1" />
					<avprule name="MIP-FA-to-MN-Key" maximum="1" />
					<avprule name="MIP-FA-to-HA-Key" maximum="1" />
					<avprule name="MIP-HA-to-MN-Key" maximum="1" />
					<avprule name="MIP-HA-to-FA-Key" maximum="1" />
					<avprule name="MIP-Key-Lifetime" maximum="1" />
					<avprule name="MIP-Home-Agent-Address" maximum="1" />
					<avprule name="MIP-Mobile-Node-Address" maximum="1" />
					<!--avprule name="MIP-Filter-Rule"/-->
					<avprule name="Origin-State-Id" maximum="1" />
					<avprule name="Proxy-Info" />
					<avprule name="AVP" />
				</optional>
			</answerrules>
		</command>
		<command name="Home-Agent-MIP" code="262">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1" />
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1" />
					<avprule name="Authorization-Lifetime" maximum="1" minimum="1" />
					<avprule name="Auth-Session-State" maximum="1" minimum="1" />
					<avprule name="MIP-Reg-Request" maximum="1" minimum="1" />
					<avprule name="Origin-Host" maximum="1" minimum="1" />
					<avprule name="Origin-Realm" maximum="1" minimum="1" />
					<avprule name="User-Name" maximum="1" minimum="1" />
					<avprule name="Destination-Realm" maximum="1" minimum="1" />
					<avprule name="MIP-Feature-Vector" maximum="1" minimum="1" />
				</required>
				<optional>
					<avprule name="Destination-Host" maximum="1" />
					<avprule name="MIP-MN-to-HA-Key" maximum="1" />
					<avprule name="MIP-MN-to-FA-Key" maximum="1" />
					<avprule name="MIP-HA-to-MN-Key" maximum="1" />
					<avprule name="MIP-HA-to-FA-Key" maximum="1" />
					<avprule name="MIP-Key-Lifetime" maximum="1" />
					<avprule name="MIP-Originating-Foreign-AAA" maximum="1" />
					<avprule name="MIP-Mobile-Node-Address" maximum="1" />
					<avprule name="MIP-Home-Agent-Address" maximum="1" />
					<!--avprule name="MIP-Filter-Rule"/-->
					<avprule name="Origin-State-Id" maximum="1" />
					<avprule name="Proxy-Info" />
					<avprule name="Route-Record" />
					<avprule name="AVP" />
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1" />
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1" />
					<avprule name="Result-Code" maximum="1" minimum="1" />
					<avprule name="Origin-Host" maximum="1" minimum="1" />
					<avprule name="Origin-Realm" maximum="1" minimum="1" />
				</required>
				<optional>
					<avprule name="Acct-Multi-Session-Id" maximum="1" />
					<avprule name="User-Name" maximum="1" />
					<avprule name="Error-Reporting-Host" maximum="1" />
					<avprule name="Error-Message" maximum="1" />
					<avprule name="MIP-Reg-Reply" maximum="1" />
					<avprule name="MIP-Home-Agent-Address" maximum="1" />
					<avprule name="MIP-Mobile-Node-Address" maximum="1" />
					<avprule name="MIP-FA-to-HA-SPI" maximum="1" />
					<avprule name="MIP-FA-to-MN-SPI" maximum="1" />
					<avprule name="Origin-State-Id" maximum="1" />
					<avprule name="Proxy-Info" />
					<avprule name="AVP" />
				</optional>
			</answerrules>
		</command>

		<avp name="MIP-Auth-Input-Data-Length" code="338" mandatory="must">
			<type type-name="Unsigned32" />
		</avp>
		<avp name="MIP-Authenticator-Length" code="339" mandatory="must">
			<type type-name="Unsigned32" />
		</avp>
		<avp name="MIP-Authenticator-Offset" code="340" mandatory="must">
			<type type-name="Unsigned32" />
		</avp>
		<avp name="MIP-Candidate-Home-Agent-Host" code="336" mandatory="must">
			<type type-name="DiameterIdentity" />
		</avp>
		<avp name="MIP-Home-Agent-Host" code="348" mandatory="must">
			<type type-name="DiameterIdentity" />
		</avp>
		<avp name="MIP-FA-Challenge" code="344" mandatory="must">
			<type type-name="OctetString" />
		</avp>
		<avp name="MIP-Feature-Vector" code="337" mandatory="must">
			<type type-name="Unsigned32" />
		</avp>
		<avp name="MIP-Home-Agent-Address" code="334" mandatory="must">
			<type type-name="Address" />
		</avp>
		<avp name="MIP-MN-AAA-SPI" code="341" mandatory="must">
			<type type-name="Unsigned32" />
		</avp>
		<avp name="MIP-Mobile-Node-Address" code="333" mandatory="must">
			<type type-name="Address" />
		</avp>
		<avp name="MIP-Reg-Request" code="320" mandatory="must">
			<type type-name="OctetString" />
		</avp>
		<avp name="MIP-Reg-Reply" code="321" mandatory="must">
			<type type-name="OctetString" />
		</avp>
		<avp name="MIP-MN-AAA-Auth" code="322" mandatory="must">
			<grouped>
				<required>
					<avprule name="MIP-MN-AAA-SPI" maximum="1" minimum="1" />
					<avprule name="MIP-Auth-Input-Data-Length" maximum="1" minimum="1" />
					<avprule name="MIP-Authenticator-Offset" maximum="1" minimum="1" />
				</required>
				<optional>
					<avprule name="AVP" />
				</optional>
			</grouped>
		</avp>
		<avp name="MIP-Originating-Foreign-AAA" code="347" mandatory="must">
			<grouped>
				<required>
					<avprule name="Origin-Realm" maximum="1" minimum="1" />
					<avprule name="Origin-Host" maximum="1" minimum="1" />
				</required>
				<optional>
					<avprule name="AVP" />
				</optional>
			</grouped>
		</avp>
		<avp name="MIP-Algorithm-Type" code="345" mandatory="must">
			<type type-name="Enumerated" />
		</avp>
		<avp name="MIP-FA-to-HA-SPI" code="318" mandatory="must">
			<type type-name="Unsigned32" />
		</avp>
		<avp name="MIP-FA-to-MN-SPI" code="319" mandatory="must">
			<type type-name="Unsigned32" />
		</avp>
		<avp name="MIP-Replay-Mode" code="346" mandatory="must">
			<type type-name="Enumerated" />
		</avp>
		<avp name="MIP-Session-Key" code="343" mandatory="must">
			<type type-name="OctetString" />
		</avp>
		<avp name="MIP-FA-to-MN-Key" code="326" mandatory="must">
			<grouped>
				<required>
					<avprule name="MIP-FA-to-MN-SPI" maximum="1" minimum="1" />
					<avprule name="MIP-Algorithm-Type" maximum="1" minimum="1" />
					<avprule name="MIP-Session-Key" maximum="1" minimum="1" />
				</required>
				<optional>
					<avprule name="AVP" />
				</optional>
			</grouped>
		</avp>
		<avp name="MIP-FA-to-HA-Key" code="328" mandatory="must">
			<grouped>
				<required>
					<avprule name="MIP-FA-to-HA-SPI" maximum="1" minimum="1" />
					<avprule name="MIP-Algorithm-Type" maximum="1" minimum="1" />
					<avprule name="MIP-Session-Key" maximum="1" minimum="1" />
				</required>
				<optional>
					<avprule name="AVP" />
				</optional>
			</grouped>
		</avp>
		<avp name="MIP-HA-to-FA-Key" code="329" mandatory="must">
			<grouped>
				<required>
					<avprule name="MIP-Algorithm-Type" maximum="1" minimum="1" />
					<avprule name="MIP-Session-Key" maximum="1" minimum="1" />
				</required>
				<optional>
					<avprule name="AVP" />
				</optional>
			</grouped>
		</avp>
		<avp name="MIP-HA-to-MN-Key" code="332" mandatory="must">
			<grouped>
				<required>
					<avprule name="MIP-Algorithm-Type" maximum="1" minimum="1" />
					<avprule name="MIP-Replay-Mode" maximum="1" minimum="1" />
					<avprule name="MIP-Session-Key" maximum="1" minimum="1" />
				</required>
				<optional>
					<avprule name="AVP" />
				</optional>
			</grouped>
		</avp>
		<avp name="MIP-Key-Lifetime" code="367" mandatory="must">
			<type type-name="Unsigned32" />
		</avp>
		<avp name="MIP-Key-Material" code="335" mandatory="must">
